### ISSUE TITLE
Audio on Linux has some problem. Also, SDL2 audio APIs are deprecated.

### ISSUE THREAD

**Issue by AndreaOrru** [AndreaOrru/LaiNES#13]

**Comment by kraln** [comment]
Is the problem "Extreme choppyness?" if so, I am experiencing this and will investigate.

**Comment by AndreaOrru** [comment]
It is. I just switched back to Linux actually, so I can have a look too.

**Comment by AndreaOrru** [comment]
621aa65858ec6eaae33f051cd0041e4d95df9354 should solve this. Hopefully it doesn't break on Mac.

**Comment by kraln** [comment]
Issue still present on my machine: 
Linux galium 4.8.3-1-ARCH #1 SMP PREEMPT Thu Oct 20 19:53:59 CEST 2016 x86_64 GNU/Linux

Compiler:
clang version 3.8.1 (tags/RELEASE_381/final)

Computer:
Thinkpad L460

Here's a .FLAC -- you can see the audio output is *really* choppy.
[test.zip](https://github.com/AndreaOrru/LaiNES/files/626874/test.zip)

**Comment by AndreaOrru** [comment]
Ok. It solved it on mine. I'll borrow another Linux machine and experiment more.

**Comment by kraln** [comment]
I started to poke around a bit. When I run the APU for twice as many cycles, it seems to be better. When I run it at a lower sample rate (= lowpass filter), it seems to be much better.

https://github.com/kraln/LaiNES/tree/investigating_audio

**Comment by AndreaOrru** [comment]
Thanks. I won't have a lot of time to work on this till at least the 21st of December. Your contributions are super appreciated. :)

**Comment by RyanPattison** [comment]
In Ubuntu, entering  `export SDL_AUDIODRIVER=ALSA` before running improves the audio by a lot.

**Comment by AndreaOrru** [comment]
Thanks, that's good to know! I'll write that in the README.

**Comment by kraln** [comment]
After #49 I can't tell the difference between with and without `SDL_AUDIODRIVER=ALSA`--it's no longer choppy
